server:
  port: 8081

  #spring:
  #  cloud:
  #    discovery:
  #      enabled: true
  #  application:
  #    name: api

datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres
  driverClassName: org.postgresql.Driver

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

jwt:
  token_secret: MegaLargeSigningSecretKeyForDemoApplicationMegaLargeSigningSecretKeyForDemoApplication
  token_expired: 3600000
